### ISSUE TITLE
Missing Table?

### ISSUE THREAD

**Issue by 007wozza007** [dwalton76/rubiks-cube-lookup-tables-6x6x6#1]
Attempted to run the NxNxN solver however received this exception:

2018-01-01 18:01:06,095   LookupTable.py     INFO: Downloading table via 'wget https://github.com/dwalton76/rubiks-cube-lookup-tables-6x6x6/raw/master/lookup-table-6x6x6-step60-LFRB-solve-inner-x-center-and-oblique-edges.txt.gz.part-ac'
--2018-01-01 18:01:06--  https://github.com/dwalton76/rubiks-cube-lookup-tables-6x6x6/raw/master/lookup-table-6x6x6-step60-LFRB-solve-inner-x-center-and-oblique-edges.txt.gz.part-ac
Resolving github.com (github.com)... 192.30.253.112, 192.30.253.113
Connecting to github.com (github.com)|192.30.253.112|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2018-01-01 18:01:06 ERROR 404: Not Found.

Suspect this repo is missing a the table lookup-table-6x6x6-step60-LFRB-solve-inner-x-center-and-oblique-edges.txt.gz.part-ac? 

PS - great work, love the solver so far!! :)

**Comment by dwalton76** [comment]
Hey @007wozza007, this is resolved now but you'll need to do a `git pull` in your https://github.com/dwalton76/rubiks-cube-NxNxN-solver repo.  The 6x6x6-step60 table no longer needs the `part-ac` part of the file, it is only split into `part-aa` and `part-ab`.

Glad you are enjoying the solver :+1:
